// <auto-generated />
namespace DiscussionApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CutoutTelevisionandSports : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CutoutTelevisionandSports));
        
        string IMigrationMetadata.Id
        {
            get { return "201906051347363_Cut out Television and Sports"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
